# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: push
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Get package values
      uses: jarrettmeyer/github-action-package-values@v1
      id: pkg
    - run: npm install
    - run: npm run build
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: '${{ steps.pkg.outputs.package_name }}.zip'
        path: './dist/*'
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.pkg.outputs.package_name }}
        path: ${{ github.workspace }}/${{ steps.pkg.outputs.package_name }}.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ steps.pkg.outputs.package_name }}.zip
